# Generated by Django 5.1.7 on 2025-07-24 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0039_documentitem_unit_conversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва посади')),
                ('description', models.TextField(blank=True, verbose_name="Опис обов'язків")),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Погодинна ставка (грн)')),
            ],
            options={
                'verbose_name': 'Посада працівника',
                'verbose_name_plural': 'Посади працівників',
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва зміни')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час закінчення')),
                ('work_days', models.JSONField(default=list, help_text='Список днів тижня: [1,2,3,4,5] для пн-пт', verbose_name='Робочі дні')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Робоча зміна',
                'verbose_name_plural': 'Робочі зміни',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва лінії')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('capacity_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Скільки одиниць продукції може виробити за годину', max_digits=10, verbose_name='Потужність (од/год)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Технічне обслуговування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
                ('warehouse', models.ForeignKey(help_text='Склад де знаходиться лінія', on_delete=django.db.models.deletion.CASCADE, to='backend.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Виробнича лінія',
                'verbose_name_plural': 'Виробничі лінії',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва центру')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('work_type', models.CharField(choices=[('preparation', 'Підготовка'), ('processing', 'Обробка'), ('assembly', 'Збірка'), ('packaging', 'Пакування'), ('quality_control', 'Контроль якості'), ('storage', 'Зберігання')], max_length=20, verbose_name='Тип роботи')),
                ('setup_time_minutes', models.IntegerField(default=0, help_text='Час підготовки робочого місця', verbose_name='Час налаштування (хв)')),
                ('capacity_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Потужність (од/год)')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість роботи (грн/год)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_centers', to='production.productionline', verbose_name='Виробнича лінія')),
            ],
            options={
                'verbose_name': 'Робочий центр',
                'verbose_name_plural': 'Робочі центри',
                'unique_together': {('production_line', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва обладнання')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серійний номер')),
                ('status', models.CharField(choices=[('operational', 'Працює'), ('maintenance', 'Обслуговування'), ('broken', 'Несправне'), ('idle', 'Простоює')], default='operational', max_length=20, verbose_name='Статус')),
                ('power_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Споживання енергії (кВт/год)')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата придбання')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Вартість придбання')),
                ('maintenance_interval_hours', models.IntegerField(default=0, help_text='Через скільки годин роботи потрібне технічне обслуговування', verbose_name='Інтервал ТО (години)')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Останнє ТО')),
                ('next_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='Наступне ТО')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='production.workcenter', verbose_name='Робочий центр')),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Обладнання',
            },
        ),
        migrations.CreateModel(
            name='ProductionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Табельний номер')),
                ('skill_level', models.IntegerField(choices=[(1, 'Рівень 1'), (2, 'Рівень 2'), (3, 'Рівень 3'), (4, 'Рівень 4'), (5, 'Рівень 5')], default=1, verbose_name='Рівень кваліфікації')),
                ('hire_date', models.DateField(verbose_name='Дата прийняття на роботу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_worker', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('work_centers', models.ManyToManyField(help_text='На яких робочих місцях може працювати', to='production.workcenter', verbose_name='Робочі центри')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workerposition', verbose_name='Посада')),
            ],
            options={
                'verbose_name': 'Виробничий працівник',
                'verbose_name_plural': 'Виробничі працівники',
            },
        ),
    ]
