# Generated by Django 5.1.7 on 2025-07-24 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_documentitem_unit_conversion'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date_from', models.DateField(verbose_name='Дата початку')),
                ('plan_date_to', models.DateField(verbose_name='Дата закінчення')),
                ('name', models.CharField(max_length=255, verbose_name='Назва плану')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Затверджено'), ('in_progress', 'Виконується'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Затверджено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_production_plans', to=settings.AUTH_USER_MODEL, verbose_name='Затвердив')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_plans', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
            ],
            options={
                'verbose_name': 'План виробництва',
                'verbose_name_plural': 'Плани виробництва',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер замовлення')),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Замовлена кількість')),
                ('quantity_produced', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Вироблено')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата замовлення')),
                ('due_date', models.DateTimeField(verbose_name='Термін виконання')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок виробництва')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('planned', 'Заплановано'), ('released', 'Запущено'), ('in_progress', 'Виконується'), ('completed', 'Завершено'), ('cancelled', 'Скасовано'), ('on_hold', 'Призупинено')], default='draft', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('normal', 'Звичайний'), ('high', 'Високий'), ('urgent', 'Терміновий')], default='normal', max_length=10, verbose_name='Пріоритет')),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Планова собівартість')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фактична собівартість')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionworker', verbose_name='Призначено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionline', verbose_name='Виробнича лінія')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcalculation', verbose_name='Рецепт/технологічна карта')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders_source', to='backend.warehouse', verbose_name='Склад сировини')),
                ('target_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders_target', to='backend.warehouse', verbose_name='Склад готової продукції')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionplan', verbose_name='План виробництва')),
            ],
            options={
                'verbose_name': 'Виробниче замовлення',
                'verbose_name_plural': 'Виробничі замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Планована кількість')),
                ('planned_start_date', models.DateTimeField(verbose_name='Планований початок')),
                ('planned_end_date', models.DateTimeField(verbose_name='Планове закінчення')),
                ('priority', models.IntegerField(choices=[(1, 'Пріоритет 1'), (2, 'Пріоритет 2'), (3, 'Пріоритет 3'), (4, 'Пріоритет 4'), (5, 'Пріоритет 5')], default=3, help_text='1 - найвищий, 5 - найнижчий', verbose_name='Пріоритет')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Планова собівартість')),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Планова тривалість (год)')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionline', verbose_name='Виробнича лінія')),
                ('production_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionplan', verbose_name='План виробництва')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcalculation', verbose_name='Рецепт/технологічна карта')),
            ],
            options={
                'verbose_name': 'Позиція плану виробництва',
                'verbose_name_plural': 'Позиції планів виробництва',
                'unique_together': {('production_plan', 'recipe', 'production_line')},
            },
        ),
    ]
