# Generated by Django 5.1.7 on 2025-07-24 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_chartofaccounts_costcenter_accountingentry'),
        ('production', '0002_productionplan_productionorder_productionplanitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва ТО')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('frequency_type', models.CharField(choices=[('hours', 'По мотогодинах'), ('days', 'По днях'), ('cycles', 'По циклах роботи'), ('manual', 'Ручне планування')], default='days', max_length=20, verbose_name='Тип періодичності')),
                ('frequency_value', models.IntegerField(default=30, verbose_name='Значення періодичності')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Тривалість (год)')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Планова вартість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тип ТО',
                'verbose_name_plural': 'Типи ТО',
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва типу')),
                ('category', models.CharField(choices=[('defect', 'Брак'), ('waste', 'Відходи'), ('rework', 'На доробку')], default='defect', max_length=20, verbose_name='Категорія')),
                ('is_recoverable', models.BooleanField(default=False, verbose_name='Можна відновити')),
                ('recovery_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість відновлення за од.')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип браку/відходів',
                'verbose_name_plural': 'Типи браку та відходів',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Планова дата')),
                ('estimated_duration', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Планова тривалість (год)')),
                ('status', models.CharField(choices=[('scheduled', 'Заплановано'), ('in_progress', 'Виконується'), ('completed', 'Завершено'), ('cancelled', 'Скасовано'), ('overdue', 'Прострочено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактичний початок')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактичне завершення')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фактична вартість')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Примітки по виконанню')),
                ('next_maintenance_date', models.DateTimeField(blank=True, null=True, verbose_name='Наступне ТО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='production.productionline', verbose_name='Виробнича лінія')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.maintenancetype', verbose_name='Тип ТО')),
            ],
            options={
                'verbose_name': 'График ТО',
                'verbose_name_plural': 'Графіки ТО',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва контрольної точки')),
                ('check_type', models.CharField(choices=[('visual', 'Візуальний контроль'), ('measurement', 'Вимірювання'), ('testing', 'Тестування'), ('sampling', 'Вибіркова перевірка')], default='visual', max_length=20, verbose_name='Тип перевірки')),
                ('check_frequency', models.CharField(choices=[('each', 'Кожна одиниця'), ('batch', 'Кожна партія'), ('hour', 'Кожну годину'), ('shift', 'Кожну зміну')], default='batch', max_length=20, verbose_name='Частота перевірки')),
                ('criteria', models.TextField(verbose_name='Критерії якості')),
                ('acceptable_deviation', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Допустиме відхилення (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checkpoints', to='production.productionline', verbose_name='Виробнича лінія')),
            ],
            options={
                'verbose_name': 'Контрольна точка',
                'verbose_name_plural': 'Контрольні точки',
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата перевірки')),
                ('checked_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Перевірено (шт)')),
                ('passed_quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Пройшло контроль')),
                ('failed_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Не пройшло контроль')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Виміряне значення')),
                ('deviation_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Відхилення (%)')),
                ('status', models.CharField(choices=[('pass', 'Пройшов'), ('fail', 'Не пройшов'), ('conditional', 'Умовно пройшов')], default='pass', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Контролер')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.productionorder', verbose_name='Виробниче замовлення')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.qualitycheckpoint', verbose_name='Контрольна точка')),
            ],
            options={
                'verbose_name': 'Контроль якості',
                'verbose_name_plural': 'Контроль якості',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість за од.')),
                ('total_loss', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Загальні втрати')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час виявлення')),
                ('cause_category', models.CharField(choices=[('material', 'Сировина'), ('equipment', 'Обладнання'), ('process', 'Технологічний процес'), ('human', 'Людський фактор'), ('environment', 'Зовнішні фактори')], default='process', max_length=20, verbose_name='Категорія причини')),
                ('cause_description', models.TextField(verbose_name='Опис причини')),
                ('action_taken', models.TextField(blank=True, verbose_name='Вжиті заходи')),
                ('is_recovered', models.BooleanField(default=False, verbose_name='Відновлено')),
                ('recovery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість відновлення')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='production.productionorder', verbose_name='Виробниче замовлення')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто повідомив')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.unit', verbose_name='Одиниця виміру')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.workcenter', verbose_name='Робочий центр')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.wastetype', verbose_name='Тип браку/відходів')),
            ],
            options={
                'verbose_name': 'Запис про брак/відходи',
                'verbose_name_plural': 'Облік браку та відходів',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimeNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_time_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Час на підготовку лінії для виробництва', max_digits=8, verbose_name='Час налаштування (хв)')),
                ('cycle_time_seconds', models.DecimalField(decimal_places=2, help_text='Час виробництва однієї одиниці', max_digits=8, verbose_name='Час циклу (сек)')),
                ('cleanup_time_minutes', models.DecimalField(decimal_places=2, default=0, help_text='Час на прибирання після завершення', max_digits=8, verbose_name='Час прибирання (хв)')),
                ('efficiency_factor', models.DecimalField(decimal_places=3, default=0.85, help_text='Врахування втрат часу (0.85 = 85% ефективність)', max_digits=4, verbose_name='Коефіцієнт ефективності')),
                ('quality_factor', models.DecimalField(decimal_places=3, default=0.95, help_text='Врахування браку (0.95 = 5% брак)', max_digits=4, verbose_name='Коефіцієнт якості')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Діє з')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Діє до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Продукт')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_norms', to='production.productionline', verbose_name='Виробнича лінія')),
            ],
            options={
                'verbose_name': 'Норма робочого часу',
                'verbose_name_plural': 'Норми робочого часу',
                'unique_together': {('production_line', 'product', 'valid_from')},
            },
        ),
    ]
