# Generated by Django 5.1.7 on 2025-05-02 06:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва компанії')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ЄДРПОУ / ІПН')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва клієнта')),
                ('type', models.CharField(max_length=50, verbose_name='Тип клієнта')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Відділ',
                'verbose_name_plural': 'Відділи',
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва правила')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Знижка (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Початкова дата')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Кінцева дата')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='0=Пн, ..., 6=Нд', null=True, size=None)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Час початку')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Час завершення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Правило знижки',
                'verbose_name_plural': 'Правила знижок',
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Знижка (%)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна з урахуванням знижки')),
            ],
            options={
                'verbose_name': 'Позиція документа',
                'verbose_name_plural': 'Позиції документів',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vat_type', models.CharField(choices=[('ФОП', 'ФОП'), ('ТЗОВ', 'ТЗОВ'), ('ТОВ', 'ТОВ')], max_length=20)),
            ],
            options={
                'verbose_name': 'Фірма',
                'verbose_name_plural': 'Фірма',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Інтерфейси',
                'verbose_name_plural': 'Інтерфейси',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимий залишок')),
                ('direction', models.CharField(max_length=10, verbose_name='Напрямок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Операція',
                'verbose_name_plural': 'Операції',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип оплати')),
            ],
            options={
                'verbose_name': 'Тип оплати',
                'verbose_name_plural': 'Типи оплат',
            },
        ),
        migrations.CreateModel(
            name='PriceSettingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField(help_text='Дата початку дії цін')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Затверджено')], default='draft', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Документ ціноутворення',
                'verbose_name_plural': 'Документи ціноутворення',
            },
        ),
        migrations.CreateModel(
            name='PriceSettingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Тип ціни',
                'verbose_name_plural': 'Типи цін',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ставка ПДВ')),
                ('type', models.CharField(choices=[('product', 'Товар'), ('service', 'Послуга'), ('semi', 'Напівфабрикат'), ('ingredient', 'Інгредієнт')], default='product', max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='ProductCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата дії')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
            ],
            options={
                'verbose_name': 'Калькуляція',
                'verbose_name_plural': 'Калькуляції',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Кількість')),
                ('loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Втрати при обробці (%)')),
                ('cooking_loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Втрати при термообробці (%)')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка')),
            ],
            options={
                'verbose_name': 'Компонент калькуляції',
                'verbose_name_plural': 'Компоненти калькуляції',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва групи')),
            ],
            options={
                'verbose_name': 'Група товарів',
                'verbose_name_plural': 'Групи товарів',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва постачальника')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ІПН')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
            },
        ),
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Торгова точка',
                'verbose_name_plural': 'Торгові точки',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Одиниця виміру')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Одиниця виміру',
                'verbose_name_plural': 'Одиниці виміру',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endpoint')),
                ('action', models.CharField(max_length=100, verbose_name='Дія')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Аудит лог',
                'verbose_name_plural': 'Аудит логи',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_profiles', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
            ],
            options={
                'verbose_name': 'Користувачі системи',
                'verbose_name_plural': 'Користувачі системи',
            },
        ),
        migrations.CreateModel(
            name='DepartmentWarehouseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.department')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('receipt', 'Поступлення'), ('sale', 'Реалізація'), ('return_from_client', 'Повернення від клієнта'), ('return_to_supplier', 'Повернення постачальнику'), ('transfer', 'Переміщення'), ('inventory', 'Інвентаризація'), ('stock_in', 'Оприбуткування')], max_length=30, verbose_name='Тип документа')),
                ('doc_number', models.CharField(max_length=50, unique=True, verbose_name='Номер документа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('status', models.CharField(default='draft', max_length=20, verbose_name='Статус')),
                ('auto_payment', models.BooleanField(default=False, verbose_name='Автоматична оплата')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
            ],
            options={
                'permissions': [('create_receipt', 'Can create Receipt'), ('view_receipt', 'Can view Receipt'), ('edit_receipt', 'Can edit Receipt'), ('delete_receipt', 'Can delete Receipt'), ('create_sale', 'Can create Sale'), ('view_sale', 'Can view Sale'), ('edit_sale', 'Can edit Sale'), ('delete_sale', 'Can delete Sale'), ('create_return_from_client', 'Can create Return From Client'), ('view_return_from_client', 'Can view Return From Client'), ('edit_return_from_client', 'Can edit Return From Client'), ('delete_return_from_client', 'Can delete Return From Client'), ('create_return_to_supplier', 'Can create Return To Supplier'), ('view_return_to_supplier', 'Can view Return To Supplier'), ('edit_return_to_supplier', 'Can edit Return To Supplier'), ('delete_return_to_supplier', 'Can delete Return To Supplier'), ('create_transfer', 'Can create Transfer'), ('view_transfer', 'Can view Transfer'), ('edit_transfer', 'Can edit Transfer'), ('delete_transfer', 'Can delete Transfer'), ('create_inventory', 'Can create Inventory'), ('view_inventory', 'Can view Inventory'), ('edit_inventory', 'Can edit Inventory'), ('delete_inventory', 'Can delete Inventory'), ('create_stock_in', 'Can create Stock In'), ('view_stock_in', 'Can view Stock In'), ('edit_stock_in', 'Can edit Stock In'), ('delete_stock_in', 'Can delete Stock In')],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
