# Generated by Django 5.1.7 on 2025-05-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0001_initial'),
        ('kkm', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlements.contract'),
        ),
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer', verbose_name='Клієнт'),
        ),
        migrations.AddField(
            model_name='document',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkm.cashshift', verbose_name='Зміна'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.document', verbose_name='Документ-джерело'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='firm',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
        ),
        migrations.AddField(
            model_name='document',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма'),
        ),
        migrations.AddField(
            model_name='department',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm'),
        ),
        migrations.AddField(
            model_name='interface',
            name='access_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='interfaces',
            field=models.ManyToManyField(to='backend.interface'),
        ),
        migrations.AddField(
            model_name='operation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='operation',
            name='source_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.operation', verbose_name='Партія'),
        ),
        migrations.AddField(
            model_name='pricesettingdocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='price_setting_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.pricesettingdocument', verbose_name='Документ ціноутворення'),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='price_setting_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.pricesettingdocument'),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='price_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pricetype'),
        ),
        migrations.AddField(
            model_name='product',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма-власник'),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product'),
        ),
        migrations.AddField(
            model_name='operation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='products',
            field=models.ManyToManyField(blank=True, to='backend.product', verbose_name='Товари (опц.)'),
        ),
        migrations.AddField(
            model_name='productcalculation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='backend.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productcalculationitem',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.productcalculation', verbose_name='Калькуляція'),
        ),
        migrations.AddField(
            model_name='productcalculationitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Компонент (інгредієнт або напівфабрикат)'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.productgroup', verbose_name='Батьківська група'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productgroup', verbose_name='Група товару'),
        ),
        migrations.AddField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier', verbose_name='Постачальник'),
        ),
        migrations.AddField(
            model_name='tradepoint',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='trade_points',
            field=models.ManyToManyField(blank=True, to='backend.tradepoint', verbose_name='Торгові точки (опц.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit', verbose_name='Одиниця виміру'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.unit', verbose_name='Одиниця виміру'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company'),
        ),
        migrations.AddField(
            model_name='operation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='document',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_docs', to='backend.warehouse', verbose_name='Склад призначення'),
        ),
        migrations.AddField(
            model_name='document',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='departmentwarehouseaccess',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='pricesettingitem',
            unique_together={('price_setting_document', 'product', 'price_type')},
        ),
    ]
