# Generated by Django 5.1.7 on 2025-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesettingitem',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='vat_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
