# Generated by Django 5.1.7 on 2025-05-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pricesettingitem_markup_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='converted_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Кількість (баз.)'),
        ),
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Фактор конвертації')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conversions', to='backend.unit', verbose_name='З од.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Товар')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='backend.unit', verbose_name='В од.')),
            ],
            options={
                'verbose_name': 'Конвертація одиниць',
                'verbose_name_plural': 'Конвертації одиниць',
                'unique_together': {('product', 'from_unit', 'to_unit')},
            },
        ),
    ]
