# Generated by Django 5.1.7 on 2025-05-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_documentitem_converted_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='price_without_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна без ПДВ'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума ПДВ'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='vat_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ставка ПДВ (%)'),
        ),
    ]
