# Generated by Django 5.1.7 on 2025-05-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_documentitem_price_without_vat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': [('create_receipt', 'Can create Receipt'), ('view_receipt', 'Can view Receipt'), ('edit_receipt', 'Can edit Receipt'), ('delete_receipt', 'Can delete Receipt'), ('create_sale', 'Can create Sale'), ('view_sale', 'Can view Sale'), ('edit_sale', 'Can edit Sale'), ('delete_sale', 'Can delete Sale'), ('create_return_from_client', 'Can create Return From Client'), ('view_return_from_client', 'Can view Return From Client'), ('edit_return_from_client', 'Can edit Return From Client'), ('delete_return_from_client', 'Can delete Return From Client'), ('create_return_to_supplier', 'Can create Return To Supplier'), ('view_return_to_supplier', 'Can view Return To Supplier'), ('edit_return_to_supplier', 'Can edit Return To Supplier'), ('delete_return_to_supplier', 'Can delete Return To Supplier'), ('create_transfer', 'Can create Transfer'), ('view_transfer', 'Can view Transfer'), ('edit_transfer', 'Can edit Transfer'), ('delete_transfer', 'Can delete Transfer'), ('create_inventory', 'Can create Inventory'), ('view_inventory', 'Can view Inventory'), ('edit_inventory', 'Can edit Inventory'), ('delete_inventory', 'Can delete Inventory'), ('create_stock_in', 'Can create Stock In'), ('view_stock_in', 'Can view Stock In'), ('edit_stock_in', 'Can edit Stock In'), ('delete_stock_in', 'Can delete Stock In')], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('posted', 'Проведено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
