# Generated by Django 5.1.7 on 2025-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_document_options_alter_document_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentwarehouseaccess',
            options={'verbose_name': 'Відділ до складу ', 'verbose_name_plural': 'Відділи до складу '},
        ),
        migrations.AddField(
            model_name='documentitem',
            name='price_with_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
