# Generated by Django 5.1.7 on 2025-05-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_pricesettingitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricesettingitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='pricesettingitem',
            name='order',
        ),
    ]
