# Generated by Django 5.1.7 on 2025-05-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_pricesettingitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
            ],
            options={
                'verbose_name': 'Поступлення',
                'verbose_name_plural': 'Поступлення',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.document',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
            ],
            options={
                'verbose_name': 'Реалізація',
                'verbose_name_plural': 'Реалізація',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.document',),
        ),
    ]
