# Generated by Django 5.1.7 on 2025-05-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_receipt_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='pricesettingdocument',
            name='base_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productgroup'),
        ),
        migrations.AddField(
            model_name='pricesettingdocument',
            name='base_price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.pricetype'),
        ),
        migrations.AddField(
            model_name='pricesettingdocument',
            name='base_receipt',
            field=models.ForeignKey(blank=True, limit_choices_to={'doc_type': 'receipt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.document'),
        ),
        migrations.AddField(
            model_name='pricesettingdocument',
            name='base_type',
            field=models.CharField(blank=True, choices=[('product_group', 'Група товарів'), ('receipt', 'Документ поступлення'), ('price_type', 'Інший тип ціни')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pricesettingdocument',
            name='trade_points',
            field=models.ManyToManyField(blank=True, to='backend.tradepoint'),
        ),
    ]
