# Generated by Django 5.1.7 on 2025-05-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_delete_receipt_delete_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesettingitem',
            name='price_without_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.documentitem'),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
