# Generated by Django 5.1.7 on 2025-05-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_pricesettingitem_price_without_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettingitem',
            name='price_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.pricetype'),
        ),
    ]
