# Generated by Django 5.1.7 on 2025-05-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_pricesettingitem_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentitem',
            name='converted_quantity',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='final_price',
        ),
        migrations.AddField(
            model_name='documentitem',
            name='vat_included',
            field=models.BooleanField(default=True, verbose_name='Ціна з ПДВ'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='price_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна з ПДВ'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка ПДВ (%)'),
        ),
    ]
