# Generated by Django 5.1.7 on 2025-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_documentitem_converted_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentitem',
            name='vat_included',
        ),
        migrations.AddField(
            model_name='documentitem',
            name='converted_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Кількість (баз.)'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Знижка (%)'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна з урахуванням знижки'),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='price_with_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='vat_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ставка ПДВ (%)'),
        ),
    ]
