# Generated by Django 5.1.7 on 2025-05-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_documentitem_vat_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesettingitem',
            name='trade_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.tradepoint'),
            preserve_default=False,
        ),
    ]
