# Generated by Django 5.1.7 on 2025-05-12 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_pricesettingitem_trade_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='trade_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.tradepoint'),
        ),
        migrations.AlterUniqueTogether(
            name='pricesettingitem',
            unique_together={('price_setting_document', 'product', 'price_type', 'trade_point')},
        ),
    ]
