# Generated by Django 5.1.7 on 2025-05-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_document_trade_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='trade_point',
        ),
    ]
