# Generated by Django 5.1.7 on 2025-05-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_document_trade_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesettingitem',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.firm'),
        ),
    ]
