# Generated by Django 5.1.7 on 2025-05-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_pricesettingitem_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesettingdocument',
            name='firm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма'),
            preserve_default=False,
        ),
    ]
