# Generated by Django 5.1.7 on 2025-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_pricesettingdocument_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='role',
            field=models.CharField(blank=True, choices=[('source', 'Джерело'), ('target', 'Результат')], max_length=10, null=True, verbose_name='Роль (для фасування)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('receipt', 'Поступлення'), ('sale', 'Реалізація'), ('return_from_client', 'Повернення від клієнта'), ('return_to_supplier', 'Повернення постачальнику'), ('transfer', 'Переміщення'), ('inventory', 'Інвентаризація'), ('stock_in', 'Оприбуткування'), ('conversion', 'Фасування')], max_length=30, verbose_name='Тип документа'),
        ),
    ]
