# Generated by Django 5.1.7 on 2025-05-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_documentitem_role_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesettingitem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.unit', verbose_name='Одиниця ціни'),
            preserve_default=False,
        ),
    ]
