# Generated by Django 5.1.7 on 2025-05-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_pricesettingitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettingitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.unit', verbose_name='Одиниця ціни'),
        ),
    ]
