# Generated by Django 5.1.7 on 2025-05-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_pricesettingitem_unit_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettingitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productunitconversion'),
        ),
    ]
