# Generated by Django 5.1.7 on 2025-05-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_pricesettingitem_unit_conversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vat_rate',
        ),
    ]
