# Generated by Django 5.1.7 on 2025-05-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_product_vat_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва типу')),
            ],
            options={
                'verbose_name': 'Тип клієнта',
                'verbose_name_plural': 'Типи клієнтів',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customertype', verbose_name='Тип'),
        ),
    ]
