# Generated by Django 5.1.7 on 2025-07-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_customertype_alter_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_account', models.CharField(default='281', max_length=10, verbose_name='Рахунок товарів')),
                ('supplier_account', models.CharField(default='631', max_length=10, verbose_name='Рахунок постачальників')),
                ('vat_input_account', models.CharField(default='644', max_length=10, verbose_name='ПДВ вхідний')),
                ('client_account', models.CharField(default='361', max_length=10, verbose_name='Рахунок клієнтів')),
                ('revenue_account', models.CharField(default='701', max_length=10, verbose_name='Рахунок доходів')),
                ('vat_output_account', models.CharField(default='641', max_length=10, verbose_name='ПДВ вихідний')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
            ],
            options={
                'verbose_name': 'Налаштування обліку',
            },
        ),
    ]
