# Generated by Django 5.1.7 on 2025-07-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_accountingsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_prefix', models.CharField(default='703', max_length=10, verbose_name='Префікс поступлень')),
                ('sale_prefix', models.CharField(default='704', max_length=10, verbose_name='Префікс продажів')),
                ('return_to_supplier_prefix', models.CharField(default='RTS', max_length=10, verbose_name='Префікс повернень постачальнику')),
                ('return_from_client_prefix', models.CharField(default='RFC', max_length=10, verbose_name='Префікс повернень від клієнта')),
                ('transfer_prefix', models.CharField(default='TRF', max_length=10, verbose_name='Префікс переміщень')),
                ('inventory_prefix', models.CharField(default='INV', max_length=10, verbose_name='Префікс інвентаризації')),
                ('stock_in_prefix', models.CharField(default='STI', max_length=10, verbose_name='Префікс оприбуткування')),
                ('conversion_prefix', models.CharField(default='CNV', max_length=10, verbose_name='Префікс фасування')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_settings', to='backend.company')),
            ],
            options={
                'verbose_name': 'Налаштування документів',
            },
        ),
    ]
