# Generated by Django 5.1.7 on 2025-07-19 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_accountingsettings_default_vat_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='default_price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.pricetype', verbose_name='Тип ціни за замовчуванням'),
        ),
    ]
