# Generated by Django 5.1.7 on 2025-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_accountingsettings_default_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Собівартість одиниці', max_digits=10, verbose_name='Собівартість'),
        ),
        migrations.AddField(
            model_name='operation',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='total_sale - total_cost', max_digits=12, null=True, verbose_name='Прибуток'),
        ),
        migrations.AddField(
            model_name='operation',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна продажу одиниці', max_digits=10, null=True, verbose_name='Ціна продажу'),
        ),
        migrations.AddField(
            model_name='operation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='cost_price * quantity', max_digits=12, verbose_name='Загальна собівартість'),
        ),
        migrations.AddField(
            model_name='operation',
            name='total_sale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='sale_price * quantity', max_digits=12, null=True, verbose_name='Загальна сума продажу'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Не використовувати! Для зворотної сумісності', max_digits=10, verbose_name='Ціна (застаріле)'),
        ),
    ]
