# Generated by Django 5.1.7 on 2025-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_operation_cost_price_operation_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Тимчасово для сумісності', max_digits=10, verbose_name='Ціна (застаріле)'),
        ),
    ]
