# Generated by Django 5.1.7 on 2025-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_operation_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'verbose_name': 'Фірма', 'verbose_name_plural': 'Фірми'},
        ),
        migrations.AddField(
            model_name='firm',
            name='is_vat_payer',
            field=models.BooleanField(default=1, help_text='Чи сплачує фірма ПДВ', verbose_name='Платник ПДВ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firm',
            name='vat_type',
            field=models.CharField(choices=[('ФОП', 'ФОП (без ПДВ)'), ('ТОВ', 'ТОВ (з ПДВ)'), ('ТЗОВ', 'ТЗОВ (з ПДВ)'), ('ПАТ', 'ПАТ (з ПДВ)'), ('ПрАТ', 'ПрАТ (з ПДВ)')], max_length=20),
        ),
    ]
