# Generated by Django 5.1.7 on 2025-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_alter_firm_options_firm_is_vat_payer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('receipt', 'Поступлення'), ('inventory_in', 'Оприбуткування'), ('sale', 'Реалізація'), ('return_from_client', 'Повернення від клієнта'), ('return_to_supplier', 'Повернення постачальнику'), ('transfer', 'Переміщення'), ('inventory', 'Інвентаризація'), ('stock_in', 'Оприбуткування'), ('conversion', 'Фасування')], max_length=30, verbose_name='Тип документа'),
        ),
    ]
