# Generated by Django 5.1.7 on 2025-07-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunitconversion',
            options={'verbose_name': 'Фасування товару', 'verbose_name_plural': 'Фасування товарів'},
        ),
        migrations.AlterUniqueTogether(
            name='pricesettingitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productunitconversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricesettingitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Ціна за базову одиницю'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна за базову одиницю виміру', max_digits=10, null=True, verbose_name='Базова ціна'),
        ),
        migrations.AddField(
            model_name='productunitconversion',
            name='name',
            field=models.CharField(default=1, help_text='Пакет 100г, Упаковка 2кг', max_length=100, verbose_name='Назва фасування'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фінальна ціна'),
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='unit',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.unit', verbose_name='Одиниця ціни'),
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productunitconversion', verbose_name='Фасування (опційно)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit', verbose_name='Базова одиниця виміру'),
        ),
        migrations.AlterField(
            model_name='productunitconversion',
            name='factor',
            field=models.DecimalField(decimal_places=4, help_text='Скільки базових одиниць в одному фасуванні', max_digits=10, verbose_name='Коефіцієнт'),
        ),
        migrations.AlterField(
            model_name='productunitconversion',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conversions', to='backend.unit', verbose_name='Базова од.'),
        ),
        migrations.AlterField(
            model_name='productunitconversion',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conversions', to='backend.unit', verbose_name='Од. фасування'),
        ),
        migrations.AlterUniqueTogether(
            name='pricesettingitem',
            unique_together={('price_setting_document', 'product', 'price_type', 'trade_point', 'unit_conversion')},
        ),
        migrations.AlterUniqueTogether(
            name='productunitconversion',
            unique_together={('product', 'name')},
        ),
    ]
