# Generated by Django 5.1.7 on 2025-07-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_productunitconversion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricesettingitem',
            options={'verbose_name': 'Позиція ціноутворення', 'verbose_name_plural': 'Позиції ціноутворення'},
        ),
        migrations.RemoveField(
            model_name='pricesettingitem',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Націнка %'),
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Фінальна ціна за одиницю (з урахуванням фасування)', max_digits=12, verbose_name='Ціна продажу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='price_without_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ціна без ПДВ'),
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='unit',
            field=models.ForeignKey(default=1, editable=False, help_text='Автоматично: базова одиниця або одиниця фасування', on_delete=django.db.models.deletion.PROTECT, to='backend.unit', verbose_name='Одиниця ціни'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, help_text='Якщо не вказано - ціна за базову одиницю', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productunitconversion', verbose_name='Фасування'),
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума ПДВ'),
        ),
        migrations.AlterField(
            model_name='pricesettingitem',
            name='vat_included',
            field=models.BooleanField(default=True, verbose_name='ПДВ включено в ціну'),
        ),
    ]
