# Generated by Django 5.1.7 on 2025-07-23 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_alter_pricesettingitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettingitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Автоматично: базова одиниця або одиниця фасування', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.unit', verbose_name='Одиниця ціни'),
        ),
    ]
