# Generated by Django 5.1.7 on 2025-07-24 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_pricesettingitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productunitconversion', verbose_name='Фасування'),
        ),
    ]
