# Generated by Django 5.1.7 on 2025-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_documentitem_unit_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('receipt', 'Поступлення'), ('inventory_in', 'Оприбуткування'), ('sale', 'Реалізація'), ('return_from_client', 'Повернення від клієнта'), ('return_to_supplier', 'Повернення постачальнику'), ('transfer', 'Переміщення'), ('inventory', 'Інвентаризація'), ('stock_in', 'Оприбуткування'), ('conversion', 'Фасування'), ('production_order', 'Виробниче замовлення'), ('production', 'Виробництво'), ('production_plan', 'План виробництва'), ('work_order', 'Робоче завдання'), ('quality_control', 'Контроль якості')], max_length=30, verbose_name='Тип документа'),
        ),
    ]
