# Generated by Django 5.1.7 on 2025-07-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcalculationitem',
            options={'verbose_name': 'Позиція калькуляції', 'verbose_name_plural': 'Позиції калькуляції'},
        ),
        migrations.AddField(
            model_name='productcalculationitem',
            name='unit_conversion',
            field=models.ForeignKey(blank=True, help_text='Оберіть фасування або залиште пустим для базової одиниці', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.productunitconversion', verbose_name='Фасування'),
        ),
        migrations.AlterField(
            model_name='productcalculationitem',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.productcalculation'),
        ),
        migrations.AlterField(
            model_name='productcalculationitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='productcalculationitem',
            name='cooking_loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Втрати при готуванні %'),
        ),
        migrations.AlterField(
            model_name='productcalculationitem',
            name='loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Відходи %'),
        ),
        migrations.AlterField(
            model_name='productcalculationitem',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примітка'),
        ),
    ]
