# Generated by Django 5.1.7 on 2025-07-24 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_productcalculationitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код рахунку')),
                ('name', models.CharField(max_length=200, verbose_name='Назва рахунку')),
                ('account_type', models.CharField(choices=[('asset', 'Актив'), ('liability', 'Пасив'), ('equity', 'Капітал'), ('revenue', 'Доходи'), ('expense', 'Витрати')], max_length=20, verbose_name='Тип рахунку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_analytic', models.BooleanField(default=False, verbose_name='Аналітичний')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.chartofaccounts', verbose_name='Батьківський рахунок')),
            ],
            options={
                'verbose_name': 'Рахунок',
                'verbose_name_plural': 'План рахунків',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код ЦВ')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('center_type', models.CharField(choices=[('profit', 'Центр прибутку'), ('cost', 'Центр витрат'), ('revenue', 'Центр доходу'), ('investment', 'Центр інвестицій')], default='cost', max_length=20, verbose_name='Тип центру')),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Місячний бюджет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.costcenter', verbose_name='Батьківський ЦВ')),
            ],
            options={
                'verbose_name': 'Центр витрат',
                'verbose_name_plural': 'Центри витрат',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проводки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сума')),
                ('description', models.CharField(max_length=500, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.document')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='backend.chartofaccounts')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_entries', to='backend.chartofaccounts')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.costcenter', verbose_name='Центр витрат')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
