# Generated by Django 5.1.7 on 2025-07-24 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_chartofaccounts_costcenter_accountingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюти')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ')),
                ('is_base', models.BooleanField(default=False, verbose_name='Базова валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
            },
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='amount_currency',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Сума у валюті'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='urrency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.currency'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата курсу')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Курс')),
                ('source', models.CharField(choices=[('nbu', 'НБУ'), ('manual', 'Ручне введення'), ('bank', 'Банк'), ('api', 'API сервіс')], default='nbu', max_length=20, verbose_name='Джерело')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.currency')),
            ],
            options={
                'verbose_name': 'Курс валюти',
                'verbose_name_plural': 'Курси валют',
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
