# Generated by Django 5.1.7 on 2025-07-25 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_currency_accountingentry_amount_currency_and_more'),
        ('settlements', '0014_account_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва періоду')),
                ('start_date', models.DateField(verbose_name='Початок періоду')),
                ('end_date', models.DateField(verbose_name='Кінець періоду')),
                ('status', models.CharField(choices=[('draft', 'Проект'), ('approved', 'Затверджено'), ('active', 'Діючий'), ('closed', 'Закритий')], default='draft', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бюджетний період',
                'verbose_name_plural': 'Бюджетні періоди',
                'unique_together': {('company', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='Дата прогнозу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сума')),
                ('flow_type', models.CharField(choices=[('inflow', 'Надходження'), ('outflow', 'Витрати')], max_length=20, verbose_name='Тип потоку')),
                ('category', models.CharField(choices=[('sales', 'Продажі'), ('receivables', 'Дебіторка'), ('suppliers', 'Постачальники'), ('salaries', 'Зарплата'), ('taxes', 'Податки'), ('loans', 'Кредити'), ('investments', 'Інвестиції'), ('other', 'Інше')], max_length=50, verbose_name='Категорія')),
                ('description', models.CharField(max_length=200, verbose_name='Опис')),
                ('probability', models.IntegerField(default=100, verbose_name='Ймовірність (%)')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Фактичний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlements.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.document')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
            ],
            options={
                'verbose_name': 'Прогноз cashflow',
                'verbose_name_plural': 'Прогнози cashflow',
                'ordering': ['forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('receivables', 'Дебіторська заборгованість'), ('payables', 'Кредиторська заборгованість'), ('loan', 'Кредитні платежі'), ('lease', 'Орендні платежі'), ('recurring', 'Регулярні платежі')], max_length=20, verbose_name='Тип')),
                ('counterparty_name', models.CharField(max_length=200, verbose_name='Контрагент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сума')),
                ('due_date', models.DateField(verbose_name='Дата погашення')),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('overdue', 'Прострочено'), ('paid', 'Сплачено'), ('cancelled', 'Скасовано')], default='planned', max_length=20, verbose_name='Статус')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сплачено')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата оплати')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.document')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
            ],
            options={
                'verbose_name': 'Графік платежів',
                'verbose_name_plural': 'Графіки платежів',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Січень')),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Лютий')),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Березень')),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Квітень')),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Травень')),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Червень')),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Липень')),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Серпень')),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Вересень')),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Жовтень')),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Листопад')),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Грудень')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.chartofaccounts')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.costcenter')),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backend.budgetperiod')),
            ],
            options={
                'verbose_name': 'Стаття бюджету',
                'verbose_name_plural': 'Статті бюджету',
                'unique_together': {('budget_period', 'account', 'cost_center')},
            },
        ),
    ]
