# Generated by Django 5.1.7 on 2025-05-02 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва каси')),
                ('register_type', models.CharField(choices=[('mock', 'Тестова каса'), ('dreamkas', 'Dreamkas API'), ('ekka', 'EKKA драйвер'), ('checkbox', 'Checkbox API')], max_length=50, verbose_name='Тип каси')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='Порт')),
                ('api_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='API токен')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Логін')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tradepoint', verbose_name='Торгова точка')),
            ],
            options={
                'verbose_name': 'Каса (ККМ)',
                'verbose_name_plural': 'Каси (ККМ)',
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Час відкриття')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час закриття')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрита')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Закрив')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Відкрив')),
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tradepoint', verbose_name='Торгова точка')),
            ],
            options={
                'verbose_name': 'Сесія фірми',
                'verbose_name_plural': 'Сесії фірми',
            },
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Час відкриття')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час закриття')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрита')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='kkm.cashregister', verbose_name='Каса')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Закрив')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Відкрив')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='kkm.cashsession', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'Касова зміна',
                'verbose_name_plural': 'Касові зміни',
            },
        ),
        migrations.CreateModel(
            name='CashWorkstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва ПК')),
                ('app_key', models.CharField(max_length=100, unique=True, verbose_name='APP ключ')),
                ('role', models.CharField(choices=[('bar', 'Бар'), ('waiter', 'Офіціант'), ('front', 'Фронт'), ('kitchen', 'Кухня'), ('admin', 'Адмін')], default='front', max_length=20, verbose_name='Роль/позиція')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kkm.cashregister', verbose_name='Каса')),
            ],
            options={
                'verbose_name': 'Касовий ПК',
                'verbose_name_plural': 'Касові ПК',
            },
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фіскальний номер')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='Час друку')),
                ('status', models.CharField(choices=[('success', 'Успішно'), ('fail', 'Помилка'), ('pending', 'Очікує')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Повідомлення/помилка')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Джерело')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company', verbose_name='Компанія')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
                ('sale_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.document', verbose_name='Документ продажу')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='kkm.cashshift', verbose_name='Зміна')),
            ],
            options={
                'verbose_name': 'Фіскальний чек',
                'verbose_name_plural': 'Фіскальні чеки',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItemBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm', verbose_name='Фірма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Товар')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffer_items', to='kkm.cashshift', verbose_name='Зміна')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Буферна позиція чека',
                'verbose_name_plural': 'Буферні позиції чеків',
            },
        ),
        migrations.CreateModel(
            name='ReceiptOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Товар')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='kkm.fiscalreceipt', verbose_name='Чек')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Операція з чеку',
                'verbose_name_plural': 'Операції з чеків',
            },
        ),
    ]
