# backend/admin_group_titles.py

GROUP_TITLES = {
    "AuditLog": "🏢 Логи та дії",
    "Company": "🏢 Компанія і структура",
    "Firm": "🏢 Компанія і структура",
    "Warehouse": "🏢 Компанія і структура",
    "Department": "🏢 Компанія і структура",
    "TradePoint": "🏢 Компанія і структура",
    "DepartmentWarehouseAccess": "🏢 Компанія і структура",
    "Unit": "📦 Склад і товари",
    "ProductGroup": "📦 Склад і товари",
    "Product": "📦 Склад і товари",
    "ProductCalculation": "📦 Склад і товари",
    "ProductCalculationItem": "📦 Склад і товари",
    "DiscountRule": "📦 Склад і товари",
    "ProductUnitConversion": "📦 Склад і товари",
    "Customer": "👥 Контрагенти",
    "Supplier": "👥 Контрагенти",
    "Contract": "👥 Контрагенти",
    "PaymentType": "👥 Контрагенти",
    "PriceType": "💰 Ціноутворення",
    "PriceSettingDocument": "💰 Ціноутворення",
    "Document": "🧾 Документи",
    "DocumentItem": "🧾 Документи",
    "Operation": "🧾 Документи",
    "DocumentSettings": "🧾 Документи",
    "AccountingSettings": "🧾 Документи",
    "AppUser": "👨‍💻 Користувачі",
    "Interface": "👨‍💻 Користувачі",
    "CashRegister": "🖨 Каса (ККМ)",
    "CashShift": "🖨 Каса (ККМ)",
    "CashSession": "🖨 Каса (ККМ)",
    "FiscalReceipt": "🖨 Каса (ККМ)",
    "ReceiptOperation": "🖨 Каса (ККМ)",
    "CashWorkstation": "🖨 Каса (ККМ)",
    "VchasnoDevice": "🖨 Каса (Вчасно)",
    "VchasnoCashier": "🖨 Каса (Вчасно)",
    "VchasnoShift": "🖨 Каса (Вчасно)",
    "Account": "💵 Каса / Банк",
    "MoneyDocument": "💵 Каса / Банк",
    "MoneyOperation": "💵 Каса / Банк",
    "MoneyLedgerEntry": "💵 Каса / Банк",
    "CustomerType": "👥 Контрагенти",





}
