# Generated by Django 5.1.7 on 2025-05-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cash', 'Готівка'), ('bank', 'Банк')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
            ],
            options={
                'verbose_name': 'Каса-Банк',
                'verbose_name_plural': 'Каси-Банки',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва договору')),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договору')),
                ('contract_type', models.CharField(choices=[('partial', 'Оплата частинами'), ('prepaid', 'Оплата наперед')], max_length=50, verbose_name='Тип договору')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Діючий'), ('cancelled', 'Скасований')], default='draft', max_length=20, verbose_name='Статус')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlements.account', verbose_name='Рахунок')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.customer', verbose_name='Клієнт')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.paymenttype', verbose_name='Тип оплати')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.supplier', verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Договір',
                'verbose_name_plural': 'Договори',
            },
        ),
        migrations.CreateModel(
            name='MoneyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('cash_income', 'Надходження готівки'), ('bank_income', 'Надходження на рахунок'), ('cash_outcome', 'Витрата готівки'), ('bank_outcome', 'Витрата з рахунку')], max_length=30)),
                ('doc_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.company')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.firm')),
            ],
            options={
                'verbose_name': 'Грошовий документ',
                'verbose_name_plural': 'Грошові документи',
            },
        ),
        migrations.CreateModel(
            name='MoneyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(max_length=10)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlements.account')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlements.moneydocument')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.document')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
            ],
            options={
                'verbose_name': 'Грошова операція',
                'verbose_name_plural': 'Грошові операції',
            },
        ),
    ]
