# Generated by Django 5.1.7 on 2025-05-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0003_remove_moneyoperation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyoperation',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settlements.moneydocument'),
        ),
    ]
