# Generated by Django 5.1.7 on 2025-05-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
        ('settlements', '0005_moneydocument_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydocument',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier'),
        ),
    ]
