# Generated by Django 5.1.7 on 2025-05-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
        ('settlements', '0007_moneydocument_source_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debit_account', models.CharField(max_length=100)),
                ('credit_account', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlements.moneydocument')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
            ],
            options={
                'verbose_name': 'Проводка',
                'verbose_name_plural': 'Проводки',
            },
        ),
    ]
