# Generated by Django 5.1.7 on 2025-05-06 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pricesettingitem_markup_percent_and_more'),
        ('settlements', '0008_moneyledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydocument',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.customer'),
        ),
    ]
