# Generated by Django 5.1.7 on 2025-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0010_moneydocument_total_with_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydocument',
            name='vat_0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='moneydocument',
            name='vat_20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='moneydocument',
            name='vat_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
