# Generated by Django 5.1.7 on 2025-05-09 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0011_moneydocument_vat_0_moneydocument_vat_20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydocument',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сума до оплати'),
        ),
    ]
