# Generated by Django 5.1.7 on 2025-05-09 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0012_moneydocument_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneydocument',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settlements.account', verbose_name='Рахунок'),
        ),
        migrations.AlterField(
            model_name='moneydocument',
            name='doc_type',
            field=models.CharField(choices=[('cash_income', 'Надходження готівки'), ('bank_income', 'Надходження на рахунок'), ('cash_outcome', 'Витрата готівки'), ('bank_outcome', 'Витрата з рахунку'), ('supplier_debt', 'Борг постачальнику')], max_length=30),
        ),
    ]
