# Generated by Django 5.1.7 on 2025-07-24 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_currency_accountingentry_amount_currency_and_more'),
        ('settlements', '0013_alter_moneydocument_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.currency'),
        ),
    ]
